# Numpy

# import Libraries

In [260]:
import pandas as pd
import numpy as np

# Load Dataset

In [261]:
df = pd.read_csv(r"C:\Users\polur\Desktop\Customer Churn Analysis\Dataset\Cleaned_Data\customer_churn_Cleaned_dataset.csv")
print(df)

      Unnamed: 0  customerID  gender  SeniorCitizen Partner Dependents  \
0              0  7590-VHVEG  Female              0     Yes         No
1              1  5575-GNVDE    Male              0      No         No
2              2  3668-QPYBK    Male              0      No         No
3              3  7795-CFOCW    Male              0      No         No
4              4  9237-HQITU  Female              0      No         No
...          ...         ...     ...            ...     ...        ...
7038        7038  6840-RESVB    Male              0     Yes        Yes
7039        7039  2234-XADUH  Female              0     Yes        Yes
7040        7040  4801-JZAZL  Female              0     Yes        Yes
7041        7041  8361-LTMKD    Male              1     Yes         No
7042        7042  3186-AJIEK    Male              0      No         No

      tenure PhoneService     MultipleLines InternetService  ...  \
0          1           No  No phone service             DSL  ...
1         34          Yes                No             DSL  ...
2          2          Yes                No             DSL  ...
3         45           No  No phone service             DSL  ...
4          2          Yes                No     Fiber optic  ...
...      ...          ...               ...             ...  ...
7038      24          Yes               Yes             DSL  ...
7039      72          Yes               Yes     Fiber optic  ...
7040      11           No  No phone service             DSL  ...
7041       4          Yes               Yes     Fiber optic  ...
7042      66          Yes                No     Fiber optic  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges Total_Charges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

      Churn
0         0
1         0
2         1
3         0
4         1
...     ...
7038      0
7039      0
7040      0
7041      1
7042      0

[7043 rows x 22 columns]

In [262]:
df.head()

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Total_Charges,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [263]:
df.shape

(7043, 22)

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7043 non-null   int64
 1   customerID        7043 non-null   object
 2   gender            7043 non-null   object
 3   SeniorCitizen     7043 non-null   int64
 4   Partner           7043 non-null   object
 5   Dependents        7043 non-null   object
 6   tenure            7043 non-null   int64
 7   PhoneService      7043 non-null   object
 8   MultipleLines     7043 non-null   object
 9   InternetService   7043 non-null   object
 10  OnlineSecurity    7043 non-null   object
 11  OnlineBackup      7043 non-null   object
 12  DeviceProtection  7043 non-null   object
 13  TechSupport       7043 non-null   object
 14  StreamingTV       7043 non-null   object
 15  StreamingMovies   7043 non-null   object
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  MonthlyCharges    7043 non-null   float64
 20  Total_Charges     7043 non-null   object
 21  Churn             7043 non-null   int64
dtypes: float64(1), int64(4), object(17)
memory usage: 1.2+ MB

In [265]:
df.columns

Index(['Unnamed: 0', 'customerID', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'Total_Charges',
       'Churn'],
      dtype='object')

In [266]:
df.describe()

        Unnamed: 0  SeniorCitizen       tenure  MonthlyCharges        Churn
count  7043.000000    7043.000000  7043.000000     7043.000000  7043.000000
mean   3521.000000       0.162147    32.371149       64.761692     0.265370
std    2033.283305       0.368612    24.559481       30.090047     0.441561
min       0.000000       0.000000     0.000000       18.250000     0.000000
25%    1760.500000       0.000000     9.000000       35.500000     0.000000
50%    3521.000000       0.000000    29.000000       70.350000     0.000000
75%    5281.500000       0.000000    55.000000       89.850000     1.000000
max    7042.000000       1.000000    72.000000      118.750000     1.000000

# Convert The Numpy

In [267]:
df["SeniorCitizen"].to_numpy().dtype
df['tenure'].to_numpy()
df['MonthlyCharges'].to_numpy()
df['Churn'].to_numpy()

array([0, 0, 1, ..., 0, 1, 0], shape=(7043,))

In [268]:
len(df)

7043

In [269]:
np.array(df['SeniorCitizen'])

array([0, 0, 0, ..., 0, 1, 0], shape=(7043,))

In [270]:
np.array(df['MonthlyCharges'])

array([ 29.85,  56.95,  53.85, ...,  29.6 ,  74.4 , 105.65], shape=(7043,))

In [271]:
type('SeniorCitizen')

str

In [272]:

type('MonthlyCharges')

str

In [273]:
df['MonthlyCharges'].ndim

1

In [274]:
df["SeniorCitizen"].ndim

1

In [275]:
df['tenure'].ndim

1

In [276]:
df['Churn'].ndim

1

In [277]:
df['Churn'].shape

(7043,)

In [278]:
df['MonthlyCharges'].size

7043

In [279]:
df['Churn'].size

7043

In [280]:
df[['MonthlyCharges','Churn','tenure','SeniorCitizen']].size

28172

In [281]:
df['SeniorCitizen'].nbytes

56344

In [282]:
df['Churn'].nbytes

56344

In [283]:
df['MonthlyCharges'].nbytes

56344

In [284]:
df['MonthlyCharges'].T

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [285]:
df['Churn'].T

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [286]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [287]:
np.ones(700)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [288]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [289]:
np.full(250,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [290]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [291]:
np.identity(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [292]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Range Functions

In [293]:
np.arange(555)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554])

In [294]:
np.linspace(1,250,5)

array([  1.  ,  63.25, 125.5 , 187.75, 250.  ])

In [295]:
np.logspace(1,5,3)

array([1.e+01, 1.e+03, 1.e+05])

# Random Array

In [296]:
np.random.randn(5)

array([-0.41461575,  0.94400614, -0.46235252,  0.41144833, -1.37136687])

In [297]:
np.random.randint(1,100,10)

array([52, 77, 41, 53, 50, 15,  7, 40, 28, 32], dtype=int32)

In [298]:
np.random.random(2)

array([0.29800686, 0.62547806])

In [299]:
np.random.random(100)

array([0.15485757, 0.37299984, 0.20903704, 0.69579497, 0.94420884,
       0.99551097, 0.45027681, 0.25253039, 0.44282937, 0.84726941,
       0.20600568, 0.95209565, 0.34186577, 0.98580366, 0.83860889,
       0.80857053, 0.31790467, 0.00877721, 0.38213291, 0.30180937,
       0.03739699, 0.50536526, 0.40303131, 0.63455647, 0.62118632,
       0.12074664, 0.97696555, 0.18693143, 0.44527402, 0.48811754,
       0.8130628 , 0.0992296 , 0.42864428, 0.62850217, 0.21515562,
       0.6274679 , 0.92366484, 0.99751813, 0.03245108, 0.23558823,
       0.31030712, 0.3991261 , 0.24225716, 0.20348799, 0.95455384,
       0.9185216 , 0.0469925 , 0.33881302, 0.40514855, 0.23901453,
       0.6288729 , 0.64038075, 0.85050423, 0.74086927, 0.54257333,
       0.65358677, 0.27398878, 0.59305619, 0.48922725, 0.13334447,
       0.24254428, 0.29169345, 0.92430957, 0.23038664, 0.2892439 ,
       0.36935413, 0.66374274, 0.11823839, 0.95394521, 0.86557122,
       0.57721607, 0.67403787, 0.01666047, 0.33894478, 0.79566023,
       0.07748297, 0.28231383, 0.58529683, 0.25641303, 0.93397797,
       0.13105863, 0.79739436, 0.50794869, 0.75033078, 0.31071533,
       0.5144896 , 0.85683535, 0.4668781 , 0.35971986, 0.53615539,
       0.71736275, 0.44356335, 0.93887698, 0.29494582, 0.47546361,
       0.75692766, 0.68912109, 0.86364105, 0.99680918, 0.42685833])

In [300]:
np.random.choice(10)

6

In [301]:
np.random.choice(df['Churn'])

np.int64(1)

In [302]:
np.random.choice(df['Churn'])

np.int64(0)

In [303]:

np.random.randint(df['MonthlyCharges'])

array([ 3, 30, 43, ..., 27, 20, 91], shape=(7043,), dtype=int32)

In [304]:
np.random.seed(42)

In [305]:
np.zeros(len(df), dtype=int)

array([0, 0, 0, ..., 0, 0, 0], shape=(7043,))

# Array Indexing And Slicing

In [306]:
df['MonthlyCharges'][0]

np.float64(29.85)

In [307]:
df['MonthlyCharges'][120]

np.float64(99.8)

In [308]:
df['Churn'][5]

np.int64(1)

In [309]:
df["SeniorCitizen"][15]

np.int64(0)

In [310]:
df['tenure'][500]

np.int64(34)

In [311]:
df['tenure'][100]

np.int64(1)

# Slicing

In [312]:
df["SeniorCitizen"][15:2]

Series([], Name: SeniorCitizen, dtype: int64)

In [313]:
df['MonthlyCharges'][0:15]

0      29.85
1      56.95
2      53.85
3      42.30
4      70.70
5      99.65
6      89.10
7      29.75
8     104.80
9      56.15
10     49.95
11     18.95
12    100.35
13    103.70
14    105.50
Name: MonthlyCharges, dtype: float64

In [314]:
df['tenure'][0:10]

0     1
1    34
2     2
3    45
4     2
5     8
6    22
7    10
8    28
9    62
Name: tenure, dtype: int64

In [315]:
df['Churn'][1:5]

1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [316]:
df[['Churn'] + ['MonthlyCharges']]

      Churn  MonthlyCharges
0         0           29.85
1         0           56.95
2         1           53.85
3         0           42.30
4         1           70.70
...     ...             ...
7038      0           84.80
7039      0          103.20
7040      0           29.60
7041      1           74.40
7042      0          105.65

[7043 rows x 2 columns]

# Trigonometric Functions

In [317]:
np.sin(5)

np.float64(-0.9589242746631385)

In [318]:
np.cos(2)

np.float64(-0.4161468365471424)

In [319]:
np.tan(10)

np.float64(0.6483608274590866)

# Logarithmic

In [320]:
df.describe()

        Unnamed: 0  SeniorCitizen       tenure  MonthlyCharges        Churn
count  7043.000000    7043.000000  7043.000000     7043.000000  7043.000000
mean   3521.000000       0.162147    32.371149       64.761692     0.265370
std    2033.283305       0.368612    24.559481       30.090047     0.441561
min       0.000000       0.000000     0.000000       18.250000     0.000000
25%    1760.500000       0.000000     9.000000       35.500000     0.000000
50%    3521.000000       0.000000    29.000000       70.350000     0.000000
75%    5281.500000       0.000000    55.000000       89.850000     1.000000
max    7042.000000       1.000000    72.000000      118.750000     1.000000

In [321]:
np.log10(10)

np.float64(1.0)

In [322]:
np.log(df['MonthlyCharges'])

0       3.396185
1       4.042174
2       3.986202
3       3.744787
4       4.258446
          ...
7038    4.440296
7039    4.636669
7040    3.387774
7041    4.309456
7042    4.660132
Name: MonthlyCharges, Length: 7043, dtype: float64

In [323]:
np.exp(df['MonthlyCharges'])

0       9.197934e+12
1       5.408424e+24
2       2.436452e+23
3       2.347776e+18
4       5.065471e+30
            ...
7038    6.732433e+36
7039    6.594631e+44
7040    7.163358e+12
7041    2.048847e+32
7042    7.642088e+45
Name: MonthlyCharges, Length: 7043, dtype: float64

In [324]:
np.exp(df['SeniorCitizen'])

0       1.000000
1       1.000000
2       1.000000
3       1.000000
4       1.000000
          ...
7038    1.000000
7039    1.000000
7040    1.000000
7041    2.718282
7042    1.000000
Name: SeniorCitizen, Length: 7043, dtype: float64

In [325]:
np.round(df['tenure'])

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [326]:
df.describe()

        Unnamed: 0  SeniorCitizen       tenure  MonthlyCharges        Churn
count  7043.000000    7043.000000  7043.000000     7043.000000  7043.000000
mean   3521.000000       0.162147    32.371149       64.761692     0.265370
std    2033.283305       0.368612    24.559481       30.090047     0.441561
min       0.000000       0.000000     0.000000       18.250000     0.000000
25%    1760.500000       0.000000     9.000000       35.500000     0.000000
50%    3521.000000       0.000000    29.000000       70.350000     0.000000
75%    5281.500000       0.000000    55.000000       89.850000     1.000000
max    7042.000000       1.000000    72.000000      118.750000     1.000000

In [327]:
df['MonthlyCharges'].round(25)

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [328]:
np.floor(25)

np.int64(25)

In [329]:
np.ceil(df['SeniorCitizen'])

0       0
1       0
2       0
3       0
4       0
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: SeniorCitizen, Length: 7043, dtype: int64

In [330]:
df['tenure'].round(10)

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [331]:
df['Churn'].round(5)

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

# Statistical Functions

In [332]:
df.describe()

        Unnamed: 0  SeniorCitizen       tenure  MonthlyCharges        Churn
count  7043.000000    7043.000000  7043.000000     7043.000000  7043.000000
mean   3521.000000       0.162147    32.371149       64.761692     0.265370
std    2033.283305       0.368612    24.559481       30.090047     0.441561
min       0.000000       0.000000     0.000000       18.250000     0.000000
25%    1760.500000       0.000000     9.000000       35.500000     0.000000
50%    3521.000000       0.000000    29.000000       70.350000     0.000000
75%    5281.500000       0.000000    55.000000       89.850000     1.000000
max    7042.000000       1.000000    72.000000      118.750000     1.000000

In [333]:
df['SeniorCitizen'].count()

np.int64(7043)

In [334]:
df['SeniorCitizen'].mean()

np.float64(0.1621468124378816)

In [335]:
df['SeniorCitizen'].max()

np.int64(1)

In [336]:
df['SeniorCitizen'].min()

np.int64(0)

In [337]:
df['SeniorCitizen'].std()

np.float64(0.3686116056100131)

In [338]:
df['SeniorCitizen'].var()

np.float64(0.13587451579039184)

In [339]:
df['SeniorCitizen'].median()

np.float64(0.0)

In [340]:
np.percentile(10,10)

np.float64(10.0)

In [341]:
df['tenure'].count()

np.int64(7043)

In [342]:
df['tenure'].max()

np.int64(72)

In [343]:
df['tenure'].min()

np.int64(0)

In [344]:
df['tenure'].sum(0)

np.int64(227990)

In [345]:
df['tenure'].var()

np.float64(603.1681081237368)

In [346]:
df['tenure'].std()

np.float64(24.55948102309446)

In [347]:
df[['MonthlyCharges','Churn']].sum()

MonthlyCharges    456116.6
Churn               1869.0
dtype: float64

In [348]:
df[['MonthlyCharges','Churn']].max()

MonthlyCharges    118.75
Churn               1.00
dtype: float64

In [349]:
df[['MonthlyCharges','Churn']].min()

MonthlyCharges    18.25
Churn              0.00
dtype: float64

In [350]:
df[['MonthlyCharges','Churn']].var()

MonthlyCharges    905.410934
Churn               0.194976
dtype: float64

In [351]:
df[['MonthlyCharges','Churn']].mean()

MonthlyCharges    64.761692
Churn              0.265370
dtype: float64

In [352]:
np.average(df['SeniorCitizen'])

np.float64(0.1621468124378816)

In [353]:
np.argmax(df['Churn'])

np.int64(2)

In [354]:
np.argmin(df['tenure'])

np.int64(488)

In [355]:
np.shape(df['MonthlyCharges'])

(7043,)

In [356]:
df.shape

(7043, 22)

In [357]:
df["Churn"]

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [358]:
df['MonthlyCharges']

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [359]:
df[df['MonthlyCharges']>89.1]

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Total_Charges,Churn
5,5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,1
8,8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
12,12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1,0
13,13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,1
14,14,5129-JLPIS,Male,0,No,No,25,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7023,7023,1035-IPQPU,Female,1,Yes,No,63,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,103.50,6479.4,0
7025,7025,2823-LKABH,Female,0,No,No,18,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Month-to-month,Yes,Bank transfer (automatic),95.05,1679.4,0
7034,7034,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,1
7039,7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0
7042,7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,0

In [360]:
monthly = df["MonthlyCharges"].to_numpy()

In [361]:
np.where(monthly == 29.85)

(array([   0, 3139]),)

In [362]:
np.where(monthly > 100)

(array([   8,   12,   13,   14,   15,   17,   38,   57,   59,   60,   72,
          75,   83,   93,   94,  104,  106,  117,  142,  152,  171,  178,
         193,  197,  198,  200,  202,  208,  209,  230,  241,  256,  257,
         261,  264,  267,  273,  276,  297,  308,  312,  315,  325,  336,
         339,  357,  369,  377,  384,  396,  422,  426,  437,  440,  441,
         442,  445,  449,  455,  462,  464,  466,  483,  486,  490,  500,
         511,  513,  515,  520,  524,  526,  533,  540,  547,  548,  550,
         551,  560,  566,  568,  573,  574,  590,  603,  604,  608,  609,
         613,  617,  627,  628,  630,  635,  638,  675,  678,  683,  707,
         736,  737,  745,  746,  775,  778,  785,  807,  808,  810,  811,
         817,  818,  820,  822,  830,  841,  850,  855,  876,  880,  883,
         887,  889,  891,  896,  897,  903,  905,  909,  912,  919,  928,
         938,  944,  965,  975,  978, 1025, 1026, 1036, 1061, 1077, 1088,
        1090, 1093, 1103, 1118, 1125, 1132, 1135, 1170, 1172, 1176, 1178,
        1187, 1190, 1200, 1228, 1234, 1246, 1250, 1268, 1269, 1274, 1280,
        1283, 1287, 1293, 1300, 1306, 1313, 1339, 1345, 1357, 1385, 1394,
        1396, 1408, 1411, 1415, 1422, 1423, 1435, 1442, 1444, 1455, 1457,
        1475, 1477, 1478, 1487, 1503, 1517, 1524, 1538, 1545, 1547, 1555,
        1568, 1586, 1588, 1606, 1609, 1630, 1632, 1644, 1658, 1661, 1668,
        1671, 1673, 1678, 1693, 1701, 1702, 1719, 1735, 1744, 1746, 1749,
        1765, 1767, 1770, 1775, 1781, 1787, 1840, 1866, 1875, 1883, 1911,
        1927, 1931, 1949, 1956, 1968, 1981, 1988, 1997, 2005, 2019, 2021,
        2025, 2026, 2045, 2052, 2055, 2067, 2068, 2074, 2075, 2079, 2115,
        2135, 2146, 2149, 2157, 2164, 2177, 2182, 2187, 2203, 2204, 2208,
        2210, 2211, 2216, 2222, 2228, 2243, 2245, 2246, 2264, 2265, 2266,
        2267, 2276, 2277, 2280, 2287, 2289, 2294, 2297, 2300, 2304, 2308,
        2311, 2313, 2318, 2326, 2328, 2337, 2341, 2342, 2368, 2370, 2375,
        2379, 2380, 2387, 2393, 2416, 2424, 2438, 2443, 2448, 2450, 2451,
        2458, 2474, 2483, 2490, 2508, 2515, 2530, 2532, 2534, 2537, 2540,
        2559, 2563, 2571, 2576, 2580, 2582, 2591, 2594, 2597, 2602, 2603,
        2604, 2606, 2609, 2619, 2633, 2636, 2638, 2663, 2667, 2671, 2673,
        2684, 2685, 2689, 2708, 2730, 2731, 2737, 2739, 2743, 2766, 2785,
        2790, 2797, 2801, 2802, 2810, 2812, 2816, 2860, 2865, 2870, 2879,
        2885, 2886, 2925, 2926, 2931, 2932, 2936, 2953, 2959, 2960, 2967,
        2969, 2973, 2985, 2988, 3033, 3038, 3040, 3046, 3053, 3054, 3061,
        3063, 3075, 3085, 3107, 3108, 3111, 3112, 3117, 3137, 3147, 3164,
        3170, 3198, 3200, 3205, 3228, 3240, 3247, 3251, 3253, 3254, 3255,
        3270, 3271, 3274, 3282, 3287, 3299, 3302, 3304, 3315, 3334, 3345,
        3348, 3364, 3372, 3393, 3398, 3409, 3411, 3418, 3431, 3433, 3439,
        3445, 3446, 3450, 3460, 3472, 3473, 3476, 3503, 3508, 3514, 3517,
        3523, 3534, 3535, 3538, 3540, 3543, 3552, 3606, 3609, 3610, 3615,
        3634, 3639, 3642, 3659, 3669, 3673, 3681, 3694, 3716, 3730, 3734,
        3741, 3742, 3751, 3767, 3783, 3784, 3788, 3798, 3807, 3813, 3818,
        3820, 3829, 3830, 3837, 3838, 3849, 3854, 3856, 3861, 3863, 3864,
        3871, 3872, 3875, 3876, 3878, 3886, 3890, 3894, 3897, 3899, 3901,
        3908, 3910, 3912, 3930, 3952, 3956, 3957, 3964, 3965, 3966, 3977,
        3980, 3994, 4001, 4014, 4019, 4026, 4028, 4031, 4049, 4083, 4105,
        4134, 4144, 4155, 4164, 4169, 4170, 4181, 4186, 4188, 4191, 4199,
        4206, 4211, 4215, 4222, 4229, 4246, 4247, 4250, 4258, 4263, 4264,
        4265, 4266, 4282, 4287, 4291, 4306, 4314, 4319, 4336, 4347, 4375,
        4376, 4389, 4395, 4397, 4399, 4401, 4427, 4428, 4437, 4447, 4449,
        4459, 4490, 4500, 4519, 4533, 4535, 4547, 4553, 4554, 4562, 4566,
        4567, 4572, 4574, 4577, 4586, 4590, 4594, 4600, 4601, 4610, 4620,
        4627, 4645, 4649, 4659, 4671, 4673, 4684, 4685, 4686, 4691, 4692,
        4699, 4701, 4707, 4712, 4713, 4717, 4720, 4737, 4738, 4745, 4766,
        4786, 4792, 4797, 4804, 4807, 4822, 4826, 4835, 4838, 4850, 4855,
        4859, 4864, 4867, 4875, 4876, 4885, 4888, 4889, 4904, 4908, 4925,
        4931, 4934, 4952, 4975, 4982, 4991, 4998, 5004, 5005, 5009, 5022,
        5028, 5031, 5044, 5050, 5051, 5072, 5078, 5101, 5102, 5113, 5126,
        5127, 5133, 5137, 5138, 5142, 5154, 5166, 5178, 5187, 5188, 5190,
        5196, 5197, 5199, 5200, 5202, 5209, 5221, 5224, 5225, 5229, 5233,
        5234, 5239, 5240, 5252, 5254, 5257, 5258, 5261, 5274, 5278, 5289,
        5294, 5295, 5298, 5299, 5319, 5321, 5323, 5334, 5347, 5349, 5371,
        5372, 5373, 5394, 5405, 5414, 5420, 5425, 5433, 5444, 5448, 5449,
        5478, 5510, 5527, 5537, 5541, 5544, 5558, 5567, 5581, 5611, 5620,
        5622, 5630, 5654, 5668, 5669, 5684, 5697, 5698, 5702, 5710, 5715,
        5720, 5722, 5727, 5739, 5742, 5762, 5769, 5791, 5794, 5795, 5808,
        5813, 5818, 5819, 5834, 5848, 5851, 5874, 5877, 5894, 5916, 5922,
        5933, 5938, 5951, 5973, 5994, 5995, 5999, 6009, 6013, 6016, 6032,
        6035, 6036, 6037, 6038, 6071, 6077, 6082, 6090, 6101, 6105, 6112,
        6115, 6118, 6125, 6127, 6135, 6141, 6154, 6166, 6180, 6185, 6186,
        6193, 6196, 6203, 6225, 6232, 6236, 6242, 6255, 6264, 6278, 6289,
        6297, 6303, 6306, 6311, 6312, 6323, 6329, 6332, 6333, 6334, 6337,
        6341, 6342, 6351, 6355, 6365, 6369, 6380, 6385, 6390, 6395, 6398,
        6403, 6404, 6405, 6408, 6412, 6439, 6440, 6448, 6451, 6453, 6460,
        6477, 6478, 6482, 6496, 6497, 6501, 6526, 6533, 6535, 6537, 6544,
        6550, 6562, 6565, 6566, 6582, 6587, 6601, 6605, 6606, 6616, 6634,
        6639, 6664, 6668, 6671, 6686, 6689, 6700, 6701, 6704, 6714, 6717,
        6722, 6728, 6737, 6744, 6745, 6768, 6785, 6787, 6793, 6799, 6800,
        6805, 6808, 6833, 6839, 6853, 6859, 6860, 6876, 6883, 6886, 6894,
        6898, 6910, 6913, 6914, 6918, 6934, 6935, 6947, 6948, 6952, 6962,
        6963, 6972, 6987, 6992, 7002, 7006, 7022, 7023, 7034, 7039, 7042]),)

In [363]:
np.where(
    (monthly >= 50) & (monthly <= 100)
)[0]

array([   1,    2,    4, ..., 7036, 7038, 7041], shape=(3847,))

In [364]:
df['MonthlyCharges']

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [365]:
df.describe()

        Unnamed: 0  SeniorCitizen       tenure  MonthlyCharges        Churn
count  7043.000000    7043.000000  7043.000000     7043.000000  7043.000000
mean   3521.000000       0.162147    32.371149       64.761692     0.265370
std    2033.283305       0.368612    24.559481       30.090047     0.441561
min       0.000000       0.000000     0.000000       18.250000     0.000000
25%    1760.500000       0.000000     9.000000       35.500000     0.000000
50%    3521.000000       0.000000    29.000000       70.350000     0.000000
75%    5281.500000       0.000000    55.000000       89.850000     1.000000
max    7042.000000       1.000000    72.000000      118.750000     1.000000

# Unique & Counting

In [366]:
df['Churn'].unique()

array([0, 1])

In [367]:
np.count_nonzero(df["Churn"])

1869

In [368]:
np.bincount(df['Churn'])

array([5174, 1869])

In [369]:
df['tenure'].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [370]:
df['MonthlyCharges'].unique()

array([29.85, 56.95, 53.85, ..., 63.1 , 44.2 , 78.7 ], shape=(1585,))

In [371]:
df['SeniorCitizen'].unique()

array([0, 1])

# Missing Values Function

In [372]:
np.nanmean(df['SeniorCitizen'])

np.float64(0.1621468124378816)

In [373]:
np.nanmean(df['MonthlyCharges'])

np.float64(64.76169246059918)

In [374]:
np.isnan(df["Churn"])

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: Churn, Length: 7043, dtype: bool

In [375]:
np.isnan(df['MonthlyCharges'])

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: MonthlyCharges, Length: 7043, dtype: bool

In [376]:
np.nanmean(df['SeniorCitizen'])

np.float64(0.1621468124378816)

In [377]:
np.nanstd(df['SeniorCitizen'])

np.float64(0.36858543603093713)

In [378]:
np.nanstd(df['Churn'])

np.float64(0.44152995647932314)

In [379]:
np.nanstd(df[['Churn','SeniorCitizen']])

np.float64(0.40995818445965493)